version: "3.9"

services:
  backend:
    build: ./backend
    container_name: ztae-backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/ztae_db
    restart: always

  frontend:
    build: ./frontend
    container_name: ztae-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    command: ["--wiredTigerCacheSizeGB", "0.25"]  # limit memory for PWD
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
